data:extend({
    {
        type = "bool-setting",
        name = "sei-add-stacking-to-electric-mining-drill",
        setting_type = "startup",
        default_value = false,
        order = "a-a",
    },
    {
        type = "bool-setting",
        name = "sei-add-stacking-to-kr-electric-mining-drill-mk2",
        setting_type = "startup",
        default_value = false,
        order = "a-b",
        hidden = true,
    },
    {
        type = "bool-setting",
        name = "sei-add-stacking-to-area-mining-drill",
        setting_type = "startup",
        default_value = true,
        order = "a-c",
    },
    {
        type = "bool-setting",
        name = "sei-add-stacking-to-kr-electric-mining-drill-mk3",
        setting_type = "startup",
        default_value = true,
        order = "a-d",
        hidden = true,
    },
    {
        type = "bool-setting",
        name = "sei-add-stacking-to-aai-loaders",
        setting_type = "startup",
        default_value = true,
        order = "b-a",
        hidden = true,
    },
    {
        type = "bool-setting",
        name = "sei-add-stacking-to-kr-loaders",
        setting_type = "startup",
        default_value = true,
        order = "b-b",
        hidden = true,
    },
    {
        type = "bool-setting",
        name = "sei-loaders-wait-for-full-stack",
        setting_type = "startup",
        default_value = true,
        order = "b-c",
        hidden = true,
    },
    {
        type = "bool-setting",
        name = "sei-add-stacking-to-kr-inserters",
        setting_type = "startup",
        default_value = true,
        order = "c-a",
        hidden = true,
    },
})